import type { LevelConfig } from './LevelTypes';

export const LEVEL_FINAL_ID = 'final';

export const finalLevel: LevelConfig = {
  id: LEVEL_FINAL_ID,
  name: 'Nivel final · 7 años',
  objective: 'Recorré los recuerdos, celebrá la historia y cerrá esta aventura con amor.',
  world: {
    width: 2900,
    height: 760,
    backgroundColor: '#f7e7f7',
    backgroundStyle: 'sunset',
  },
  spawn: { x: 70, y: 548 },
  platforms: [
    { x: 260, y: 600, width: 420 },
    { x: 780, y: 540, width: 340, height: 24 },
    { x: 1040, y: 600, width: 380 },
    { x: 1480, y: 520, width: 320, height: 24 },
    { x: 1760, y: 600, width: 330 },
    { x: 2140, y: 540, width: 340, height: 24 },
    { x: 2400, y: 600, width: 420 },
    { x: 2750, y: 540, width: 370, height: 24 },
  ],
  collectibles: [
    { id: 'recuerdo-inicio', kind: 'notes', x: 310, y: 548 },
    { id: 'recuerdo-familia', kind: 'heart', x: 1160, y: 548 },
    { id: 'recuerdo-historias', kind: 'notes', x: 1810, y: 548 },
    { id: 'recuerdo-futuro', kind: 'heart', x: 2540, y: 548 },
  ],
  npcs: [
    {
      id: 'renzo-hace-siete-anos',
      label: 'RENZO',
      visual: 'renzo',
      x: 390,
      y: 548,
      dialogue: '¿Sabés algo? Hace siete años empezó todo con un simple mensaje.',
    },
    {
      id: 'renzo-cierre',
      label: 'RENZO',
      visual: 'renzo',
      x: 2280,
      y: 548,
      dialogue: 'Y pensar que todo empezó con un mensaje.',
    },
    {
      id: 'panchito-final',
      label: 'PANCHITO',
      visual: 'panchito',
      x: 1720,
      y: 570,
      dialogue: 'La familia creció y también la historia.',
    },
    {
      id: 'oliver-final',
      label: 'OLIVER',
      visual: 'oliver',
      x: 1830,
      y: 570,
      dialogue: 'O quizá simplemente nos acompañó desde el principio.',
    },
  ],
  decorations: [
    { kind: 'lamp', x: 180, y: 588 },
    { kind: 'family-photo', x: 700, y: 480 },
    { kind: 'bench', x: 980, y: 588 },
    { kind: 'window', x: 1280, y: 420 },
    { kind: 'pet-bed', x: 1550, y: 588 },
    { kind: 'box', x: 1900, y: 588 },
    { kind: 'tree', x: 2200, y: 588 },
    { kind: 'lamp', x: 2450, y: 588 },
    { kind: 'family-photo', x: 2680, y: 470 },
    { kind: 'pet', pet: 'panchito', x: 1680, y: 588 },
    { kind: 'pet', pet: 'oliver', x: 1750, y: 588 },
    { kind: 'pet', pet: 'rex', x: 1820, y: 588 },
    { kind: 'pet', pet: 'silvestre', x: 1890, y: 588 },
    { kind: 'pet', pet: 'peach', x: 1960, y: 588 },
    { kind: 'pet', pet: 'chocolatin', x: 2030, y: 588 },
    { kind: 'pet', pet: 'canelo', x: 2100, y: 588 },
    { kind: 'bench', x: 2840, y: 588 },
  ],
  exit: {
    x: 2700,
    y: 548,
    nextLevelId: null,
    completionTitle: 'VICKY — LA AVENTURA DE 7 AÑOS',
    completionScene: 'family',
    dialogue: [
      'Renzo: 7 años juntos.',
      'Vicky: 5 años de casados.',
      'Renzo: 3 hogares.',
      'Vicky: Una familia.',
      'Renzo: Muchísimos recuerdos.',
      'Vicky: Y muchísimas cosas que todavía nos quedan por vivir.',
      'Renzo: Y pensar que todo empezó con un mensaje.',
      'Vicky: Menos mal que respondí.',
      'Renzo: Menos mal que apareciste.',
      'Feliz aniversario, Vicky.',
      'Te amo. ❤️',
    ],
  },
};
