import type { LevelConfig } from './LevelTypes';

export const LEVEL_FINAL_ID = 'final';

export const finalLevel: LevelConfig = {
  id: LEVEL_FINAL_ID,
  name: 'Nivel final · 7 años',
  objective: 'Recorré los recuerdos, celebrá la historia y cerrá esta aventura con amor.',
  world: {
    width: 2900,
    height: 760,
    backgroundColor: '#f7e7f7',
    backgroundStyle: 'sunset',
  },
  spawn: { x: 70, y: 548 },
  platforms: [
    { x: 260, y: 600, width: 420 },
    { x: 780, y: 540, width: 340, height: 24 },
    { x: 1040, y: 600, width: 380 },
    { x: 1480, y: 520, width: 320, height: 24 },
    { x: 1760, y: 600, width: 330 },
    { x: 2140, y: 540, width: 340, height: 24 },
    { x: 2400, y: 600, width: 420 },
    { x: 2750, y: 540, width: 370, height: 24 },
  ],
  collectibles: [
    {
      id: 'recuerdo-inicio',
      kind: 'notes',
      x: 310,
      y: 548,
      message:
        'Todo empezó con algo tan simple como un mensaje.\nA veces las historias más importantes empiezan sin que uno se dé cuenta.',
    },
    { id: 'recuerdo-familia', kind: 'heart', x: 1160, y: 548 },
    {
      id: 'recuerdo-historias',
      kind: 'notes',
      x: 1810,
      y: 548,
      message:
        'Hubo casas, mudanzas, animales, risas, sustos, discusiones y muchísimos momentos compartidos.\nTodo eso terminó formando nuestra historia.',
    },
    { id: 'recuerdo-futuro', kind: 'heart', x: 2540, y: 548 },
  ],
  npcs: [
    {
      id: 'renzo-hace-siete-anos',
      label: 'RENZO',
      visual: 'renzo',
      x: 390,
      y: 548,
      dialogue:
        '¿Sabés qué es lo más raro de todo?\nQue hace siete años ninguno de los dos podía imaginar hasta dónde iba a llegar aquel primer mensaje.\nY acá estamos. ❤️',
    },
    {
      id: 'renzo-cierre',
      label: 'RENZO',
      visual: 'renzo',
      x: 2280,
      y: 548,
      dialogue:
        'Pasaron un montón de cosas desde aquel “Holis”.\nCambiamos de casa, llenamos todo de animales, nos casamos...\ny todavía seguimos haciendo planes juntos. ❤️',
    },
    {
      id: 'panchito-final',
      label: 'PANCHITO',
      visual: 'panchito',
      x: 1720,
      y: 570,
      dialogue:
        'Y mirá todo lo que pasó después.\nUna casa, otra casa, más animales...\ny al final terminamos siendo una familia enorme. ❤️',
    },
    {
      id: 'oliver-final',
      label: 'OLIVER',
      visual: 'oliver',
      x: 1830,
      y: 570,
      dialogue:
        'Siete años después, seguimos acá.\nBueno... yo principalmente sigo acá para asegurarme de que ninguna caja quede sin dueño. 😂',
    },
  ],
  decorations: [
    { kind: 'lamp', x: 180, y: 588 },
    { kind: 'family-photo', x: 700, y: 480 },
    { kind: 'bench', x: 980, y: 588 },
    { kind: 'window', x: 1280, y: 420 },
    { kind: 'pet-bed', x: 1550, y: 588 },
    { kind: 'box', x: 1900, y: 588 },
    { kind: 'tree', x: 2200, y: 588 },
    { kind: 'lamp', x: 2450, y: 588 },
    { kind: 'family-photo', x: 2680, y: 470 },
    { kind: 'pet', pet: 'panchito', x: 1680, y: 588 },
    { kind: 'pet', pet: 'oliver', x: 1750, y: 588 },
    { kind: 'pet', pet: 'rex', x: 1820, y: 588 },
    { kind: 'pet', pet: 'silvestre', x: 1890, y: 588 },
    { kind: 'pet', pet: 'peach', x: 1960, y: 588 },
    { kind: 'pet', pet: 'chocolatin', x: 2030, y: 588 },
    { kind: 'pet', pet: 'canelo', x: 2100, y: 588 },
    { kind: 'bench', x: 2840, y: 588 },
  ],
  exit: {
    x: 2700,
    y: 548,
    nextLevelId: null,
    completionTitle: 'VICKY — LA AVENTURA DE 7 AÑOS',
    completionScene: 'family',
    dialogue: [
      'Renzo: 7 años juntos.',
      'Vicky: 5 años de casados.',
      'Renzo: 3 hogares.',
      'Vicky: Una familia.',
      'Renzo: Y una cantidad bastante importante de animales. 😂',
      'Vicky: Demasiados para contarlos sin olvidarnos de alguno.',
      'Renzo: Y muchísimos recuerdos.',
      'Vicky: Algunos tranquilos...',
      'Vicky: ...otros bastante raros.',
      'Renzo: Algunos empezaron con un “Holis”.',
      'Vicky: Otros con un “este es el último”. 😂',
      'Renzo: Y ninguno de los dos terminó siendo realmente el último.',
      'Pero entre todas esas historias...',
      'lo más importante es que las vivimos juntos.',
      'Vicky: Y todavía nos queda muchísimo por vivir.',
      'Renzo: Porque si estos siete años fueron así...',
      '...no quiero imaginar todo lo que nos espera.',
      'Vicky: Yo sí quiero verlo.',
      'Renzo: Yo también.',
      'Y pensar que todo empezó con un mensaje.',
      'Vicky: Menos mal que respondí.',
      'Renzo: Menos mal que apareciste.',
      'Feliz aniversario, Vicky.',
      'Te amo. ❤️',
    ],
  },
};
