import type { LevelConfig } from './LevelTypes';
import { LEVEL_5_ID } from './level4';

export const LEVEL_6_ID = 'level6';

export const level5: LevelConfig = {
  id: LEVEL_5_ID,
  name: 'Nivel 5 · La casa con patio',
  objective: 'Explorá la casa y el patio, y conocé al nuevo integrante de la familia.',
  world: {
    width: 3400,
    height: 760,
    backgroundColor: '#a9def2',
    backgroundStyle: 'yard',
  },
  spawn: { x: 70, y: 548 },
  platforms: [
    { x: 1700, y: 600, width: 3400 },
    { x: 570, y: 535, width: 130, height: 24 },
    { x: 1120, y: 520, width: 150, height: 24 },
    { x: 1530, y: 545, width: 135, height: 24 },
    { x: 1900, y: 525, width: 150, height: 24 },
    { x: 2580, y: 525, width: 145, height: 24 },
  ],
  checkpoints: [
    { id: 'llegada-al-patio', x: 760, y: 548 },
    { id: 'antes-de-canelo', x: 2110, y: 548 },
  ],
  collectibles: [
    { id: 'mudanza-patio', kind: 'notes', x: 500, y: 550 },
    { id: 'recuerdo-jardin', kind: 'notes', x: 940, y: 550 },
    { id: 'corazon-ruta-elevada', kind: 'heart', x: 1190, y: 470 },
    { id: 'recuerdo-familia', kind: 'notes', x: 1690, y: 550 },
    { id: 'corazon-canelo', kind: 'heart', x: 2645, y: 475 },
  ],
  npcs: [
    {
      id: 'renzo-casa-patio',
      label: 'RENZO',
      visual: 'renzo',
      x: 375,
      y: 548,
      dialogue: 'Por fin hay lugar para caminar sin esquivar cajas… casi.',
    },
    {
      id: 'renzo-familia',
      label: 'RENZO',
      visual: 'renzo',
      x: 1760,
      y: 548,
      dialogue: 'Creo que cada uno ya eligió su rincón.',
    },
    {
      id: 'renzo-presenta-canelo',
      label: 'RENZO',
      visual: 'renzo',
      x: 2240,
      y: 548,
      dialogue: 'Quería presentarte a alguien que encontró su lugar acá.',
    },
    {
      id: 'canelo',
      label: 'CANELO',
      visual: 'canelo',
      x: 2390,
      y: 566,
      dialogue: 'Este es Canelo: blanco, marrón y… aparentemente ya eligió el patio.',
    },
    {
      id: 'renzo-canelo-cierre',
      label: 'RENZO',
      visual: 'renzo',
      x: 2520,
      y: 548,
      dialogue: '… Sí, creo que ya decidió que se queda.',
    },
  ],
  decorations: [
    { kind: 'house', x: 250, y: 588 },
    { kind: 'box', x: 505, y: 588 },
    { kind: 'sofa', x: 650, y: 588 },
    { kind: 'tree', x: 880, y: 588 },
    { kind: 'bench', x: 1040, y: 588 },
    { kind: 'tree', x: 1350, y: 588 },
    { kind: 'pet-bed', x: 1510, y: 588 },
    { kind: 'toybox', x: 1640, y: 588 },
    { kind: 'pet', pet: 'panchito', x: 1690, y: 588 },
    { kind: 'pet', pet: 'oliver', x: 1750, y: 588 },
    { kind: 'pet', pet: 'rex', x: 1815, y: 588 },
    { kind: 'pet', pet: 'silvestre', x: 1880, y: 588 },
    { kind: 'pet', pet: 'peach', x: 1940, y: 588 },
    { kind: 'pet', pet: 'chocolatin', x: 2000, y: 588 },
    { kind: 'tree', x: 2160, y: 588 },
    { kind: 'pet-bed', x: 2390, y: 588 },
    { kind: 'toybox', x: 2460, y: 588 },
    { kind: 'tree', x: 2770, y: 588 },
    { kind: 'bench', x: 2900, y: 588 },
  ],
  exit: {
    x: 3050,
    y: 548,
    nextLevelId: LEVEL_6_ID,
    completionTitle: '¡NUESTRO LUGAR! ❤️',
    completionScene: 'family',
    dialogue: [
      'La casa tenía más espacio…',
      'pero lo mejor era todo lo que compartíamos en él.',
      'Y sí… la familia volvió a crecer.',
    ],
  },
};
