import type { LevelConfig } from './LevelTypes';

export const LEVEL_4_ID = 'level-4-el-departamento';
export const LEVEL_5_ID = 'level-5-la-casa-con-patio';

export const level4: LevelConfig = {
  id: LEVEL_4_ID,
  name: 'Nivel 4 · El departamento',
  objective: 'Recorré el edificio y descubrí recuerdos de esta nueva etapa.',
  world: {
    width: 3000,
    height: 760,
    backgroundColor: '#d9d2d2',
    backgroundStyle: 'apartment',
  },
  spawn: { x: 70, y: 548 },
  platforms: [
    { x: 285, y: 600, width: 570 },
    { x: 690, y: 535, width: 130, height: 24 },
    { x: 925, y: 600, width: 420 },
    { x: 1190, y: 530, width: 150, height: 24 },
    { x: 1480, y: 600, width: 420 },
    { x: 1755, y: 535, width: 145, height: 24 },
    { x: 2025, y: 600, width: 440 },
    { x: 2300, y: 530, width: 150, height: 24 },
    { x: 2695, y: 600, width: 610 },
  ],
  checkpoints: [
    { id: 'edificio-superado', x: 1020, y: 548 },
    { id: 'antes-de-chocolatin', x: 2310, y: 480 },
  ],
  collectibles: [
    {
      id: 'mudanza-recuerdo-1',
      kind: 'notes',
      x: 340,
      y: 550,
      message: 'Nueva casa, nuevas rutinas y una cantidad sospechosa de cajas.',
    },
    {
      id: 'mudanza-recuerdo-2',
      kind: 'notes',
      x: 715,
      y: 485,
      message: 'Mudarse juntos suena romántico... hasta que toca mover todas las cosas. 😂',
    },
    {
      id: 'rutina-recuerdo-1',
      kind: 'notes',
      x: 1100,
      y: 550,
      message: 'De a poquito, aquel departamento empezó a sentirse como nuestro.',
    },
    {
      id: 'rutina-recuerdo-2',
      kind: 'notes',
      x: 1260,
      y: 480,
      message: 'Había nuevas rutinas, nuevos rincones y muchas historias por sumar.',
    },
    {
      id: 'rutina-recuerdo-3',
      kind: 'notes',
      x: 1800,
      y: 485,
      message: 'Y aunque cambiara el lugar, había algo que seguía igual: estábamos juntos. ❤️',
    },
    {
      id: 'chocolatin-recuerdo',
      kind: 'notes',
      x: 2160,
      y: 550,
      message: 'Y entonces apareció Chocolatín. Sí... otro integrante para la familia. 🐶',
    },
    {
      id: 'hogar-recuerdo',
      kind: 'notes',
      x: 2500,
      y: 550,
      message:
        'Un hogar no siempre es un lugar. A veces son todas las personas y animales que lo llenan.',
    },
    { id: 'corazon-departamento-1', kind: 'heart', x: 780, y: 485 },
    { id: 'corazon-departamento-2', kind: 'heart', x: 1850, y: 485 },
    { id: 'corazon-departamento-3', kind: 'heart', x: 2400, y: 480 },
  ],
  npcs: [
    {
      id: 'renzo-mudanza',
      label: 'RENZO',
      visual: 'renzo',
      x: 410,
      y: 548,
      dialogue:
        'Bueno... una nueva etapa.\nSolo falta acomodar estas cajas y listo.\nAunque viendo la cantidad de cosas que tenemos...\ncreo que vamos a tardar un poquito. 😂',
    },
    {
      id: 'ascensor',
      label: 'ASCENSOR',
      visual: 'elevator',
      x: 870,
      y: 548,
      dialogue:
        'Subimos, bajamos, cargamos cajas...\ny así empezó nuestra vida en el edificio.\nPor suerte, al menos el ascensor existía. 😂',
    },
    {
      id: 'renzo-chocolatin',
      label: 'RENZO',
      visual: 'renzo',
      x: 2060,
      y: 548,
      dialogue:
        'Vicky, quiero presentarte a alguien.\nBueno... alguien que está a punto de convertirse en parte de esta familia.\nY antes de que preguntes: sí, es otro animal. 😅',
    },
    {
      id: 'chocolatin',
      label: 'CHOCOLATÍN',
      visual: 'chocolatin',
      x: 2160,
      y: 566,
      dialogue:
        'Este es Chocolatín. ❤️\nLlegó para acompañarnos en esta nueva etapa.\nY como ya aprendimos...\ncuando decimos “este es el último”, probablemente no sea cierto. 😂',
    },
  ],
  decorations: [
    { kind: 'door', x: 100, y: 588 },
    { kind: 'mailboxes', x: 220, y: 470, label: 'BUZONES' },
    { kind: 'box', x: 330, y: 588 },
    { kind: 'box', x: 520, y: 588 },
    { kind: 'sofa', x: 690, y: 588 },
    { kind: 'door', x: 1120, y: 588 },
    { kind: 'window', x: 1360, y: 410 },
    { kind: 'family-photo', x: 1570, y: 438, label: 'Panchito · Oliver · Rex · Silvestre · Peach' },
    { kind: 'sofa', x: 1775, y: 588 },
    { kind: 'bed', x: 1950, y: 588 },
    { kind: 'pet-bed', x: 2160, y: 588 },
    { kind: 'toybox', x: 2240, y: 588 },
    { kind: 'lamp', x: 2420, y: 588 },
    { kind: 'window', x: 2560, y: 405 },
    { kind: 'pet', pet: 'chocolatin', x: 2660, y: 588 },
  ],
  exit: {
    x: 2800,
    y: 548,
    nextLevelId: LEVEL_5_ID,
    completionTitle: '¡NUEVA ETAPA, NUEVO HOGAR! ❤️',
    dialogue: [
      'El departamento se convirtió en nuestro nuevo escenario.',
      'Ahí tuvimos nuevas rutinas, nuevos recuerdos...',
      'y, por supuesto, más pelos de animales por todos lados. 😂',
      'También llegó Chocolatín.',
      'Y una vez más, la familia volvió a crecer.',
      'Ya teníamos nuestro hogar, nuestros animales y nuestra vida juntos.',
      'Pero todavía faltaba algo...',
      'Un poquito más de espacio.',
      'Un patio.',
      'Y, probablemente, otro animal. 😂',
      'Porque a esta altura ya deberíamos haber aprendido...',
      'cuando decimos “este es el último”... nunca es el último. ❤️',
    ],
  },
};
