import type { LevelConfig } from './LevelTypes';
import { LEVEL_4_ID } from './level4';

export const LEVEL_3_ID = 'level-3-la-primera-casa';

export const level3: LevelConfig = {
  id: LEVEL_3_ID,
  name: 'Nivel 3 · La primera casa',
  objective: 'Recorré la casa, encontrá recuerdos y conocé a la familia.',
  world: {
    width: 2800,
    height: 760,
    backgroundColor: '#ead6c6',
    backgroundStyle: 'home',
  },
  spawn: { x: 70, y: 548 },
  platforms: [
    { x: 280, y: 600, width: 560 },
    { x: 625, y: 540, width: 120, height: 24 },
    { x: 920, y: 600, width: 420 },
    { x: 1220, y: 530, width: 150, height: 24 },
    { x: 1480, y: 600, width: 390 },
    { x: 1750, y: 540, width: 140, height: 24 },
    { x: 2025, y: 600, width: 450 },
    { x: 2310, y: 540, width: 140, height: 24 },
    { x: 2585, y: 600, width: 450 },
  ],
  checkpoints: [
    { id: 'despues-de-panchito', x: 1050, y: 548 },
    { id: 'antes-del-hogar', x: 2460, y: 548 },
  ],
  collectibles: [
    { id: 'recuerdo-casa-1', kind: 'notes', x: 390, y: 550 },
    { id: 'recuerdo-casa-2', kind: 'notes', x: 675, y: 490 },
    { id: 'recuerdo-casa-3', kind: 'notes', x: 1080, y: 550 },
    { id: 'recuerdo-casa-4', kind: 'notes', x: 1260, y: 480 },
    { id: 'recuerdo-casa-5', kind: 'notes', x: 1830, y: 490 },
    { id: 'recuerdo-casa-6', kind: 'notes', x: 2250, y: 550 },
    { id: 'recuerdo-casa-7', kind: 'notes', x: 2380, y: 490 },
    { id: 'corazon-casa-1', kind: 'heart', x: 760, y: 490 },
    { id: 'corazon-casa-2', kind: 'heart', x: 1650, y: 550 },
    { id: 'corazon-casa-3', kind: 'heart', x: 2710, y: 550 },
  ],
  npcs: [
    {
      id: 'bienvenida-casa',
      label: 'NUESTRO HOGAR',
      visual: 'phone',
      x: 175,
      y: 550,
      dialogue: 'Después de conocernos, llegó el momento de compartir un lugar.',
    },
    {
      id: 'renzo-panchito',
      label: 'RENZO',
      visual: 'renzo',
      x: 710,
      y: 548,
      dialogue: 'Panchito fue el primero en llegar.\nBueno... este sí es el último.',
    },
    {
      id: 'panchito',
      label: 'PANCHITO',
      visual: 'panchito',
      x: 805,
      y: 569,
      dialogue: 'Panchito ya conocía a Vicky; ahora también empezaba a ser parte del hogar de los dos.',
    },
    {
      id: 'oliver',
      label: 'OLIVER',
      visual: 'oliver',
      x: 1300,
      y: 570,
      dialogue: 'Oliver encontró una caja cómoda. La caja, desde luego, ya era suya.',
    },
    {
      id: 'rex',
      label: 'REX',
      visual: 'rex',
      x: 1550,
      y: 562,
      dialogue: 'Rex llegó con tamaño de sobra y energía para toda la casa.',
    },
    {
      id: 'renzo-ultimo',
      label: 'RENZO',
      visual: 'renzo',
      x: 1645,
      y: 548,
      dialogue: 'Bueno... técnicamente, este también es el último.',
    },
    {
      id: 'silvestre',
      label: 'SILVESTRE',
      visual: 'silvestre',
      x: 2050,
      y: 570,
      dialogue: 'Silvestre encontró el sillón. La casa ya tenía dueño de cada rincón.',
    },
    {
      id: 'peach',
      label: 'PEACH',
      visual: 'peach',
      x: 2450,
      y: 570,
      dialogue: 'Y apareció Peach. La promesa del “último” ya empezaba a sonar sospechosa.',
    },
  ],
  decorations: [
    { kind: 'door', x: 90, y: 588 },
    { kind: 'box', x: 420, y: 588 },
    { kind: 'sofa', x: 545, y: 588 },
    { kind: 'pet-bed', x: 820, y: 588 },
    { kind: 'toybox', x: 1030, y: 588 },
    { kind: 'window', x: 1190, y: 400 },
    { kind: 'box', x: 1375, y: 588 },
    { kind: 'lamp', x: 1450, y: 588 },
    { kind: 'pet-bed', x: 1570, y: 588 },
    { kind: 'sofa', x: 1940, y: 588 },
    { kind: 'window', x: 2130, y: 400 },
    { kind: 'box', x: 2240, y: 588 },
    { kind: 'bed', x: 2395, y: 588 },
    { kind: 'pet-bed', x: 2515, y: 588 },
    { kind: 'pet', pet: 'panchito', x: 2540, y: 588 },
    { kind: 'pet', pet: 'oliver', x: 2595, y: 588 },
    { kind: 'pet', pet: 'rex', x: 2655, y: 588 },
    { kind: 'pet', pet: 'silvestre', x: 2720, y: 588 },
    { kind: 'pet', pet: 'peach', x: 2775, y: 588 },
  ],
  exit: {
    x: 2700,
    y: 548,
    nextLevelId: LEVEL_4_ID,
    completionTitle: '¡NUESTRO PRIMER HOGAR! ❤️',
    dialogue: [
      'La casa fue llenándose de pequeñas rutinas y grandes personalidades.',
      'Panchito, Oliver, Rex, Silvestre, Peach... y nosotros.',
      'Entre cajas, juguetes y promesas de que ya no habría otro animal...',
      'sin darnos cuenta, ya éramos una familia.',
      'Y todavía nos quedaban muchas etapas por vivir.',
    ],
  },
};
