import type { LevelConfig } from './LevelTypes';
import { LEVEL_2_ID } from './level2';

export const LEVEL_1_ID = 'level-1-el-match';

export const level1: LevelConfig = {
  id: LEVEL_1_ID,
  name: 'Nivel 1 · El Match',
  objective: 'Atravesá el campus universitario y descubrí qué hay en la red social 😉.',
  world: { width: 3600, height: 760, backgroundColor: '#9bdaf4', backgroundStyle: 'university' },
  spawn: { x: 70, y: 535 },
  platforms: [
    { x: 1800, y: 600, width: 3600 },
    { x: 700, y: 510, width: 150 },
    { x: 1040, y: 470, width: 170 },
    { x: 1375, y: 515, width: 180 },
    { x: 1950, y: 500, width: 180 },
    { x: 2240, y: 455, width: 170 },
    { x: 2580, y: 510, width: 190 },
    { x: 2910, y: 470, width: 170 },
    { x: 3280, y: 535, width: 240 },
  ],
  checkpoints: [
    { id: 'campus', x: 1230, y: 548 },
    { id: 'digital', x: 2670, y: 548 },
  ],
  collectibles: [
    { id: 'notes-1', kind: 'notes', x: 400, y: 550 },
    { id: 'notes-2', kind: 'notes', x: 790, y: 465 },
    { id: 'notes-3', kind: 'notes', x: 1470, y: 470 },
    { id: 'notes-4', kind: 'notes', x: 2050, y: 455 },
    { id: 'notes-5', kind: 'notes', x: 2780, y: 550 },
    { id: 'heart-1', kind: 'heart', x: 940, y: 550 },
    { id: 'heart-2', kind: 'heart', x: 2340, y: 410 },
    { id: 'star-1', kind: 'star', x: 1100, y: 415 },
    { id: 'star-2', kind: 'star', x: 3000, y: 415 },
  ],
  enemies: [{ id: 'el-parcial', kind: 'exam', x: 1760, y: 550, patrolDistance: 105, speed: 75 }],
  decorations: [
    { kind: 'university', x: 175, y: 588, label: 'UNIVERSIDAD' },
    { kind: 'tree', x: 545, y: 595 },
    { kind: 'bench', x: 835, y: 588 },
    { kind: 'sign', x: 965, y: 605, label: 'PSICOLOGÍA →' },
    { kind: 'books', x: 1130, y: 588 },
    { kind: 'tree', x: 1290, y: 588 },
    { kind: 'brain', x: 1470, y: 580 },
    { kind: 'couch', x: 2080, y: 588 },
    { kind: 'blackboard', x: 2380, y: 605, label: 'PSICOLOGÍA' },
    { kind: 'books', x: 2530, y: 588 },
    { kind: 'laptop', x: 2700, y: 588 },
    { kind: 'cable', x: 2850, y: 588 },
    { kind: 'phone', x: 3020, y: 588 },
    { kind: 'social-icons', x: 3160, y: 580, label: 'NUEVAS CONEXIONES' },
    { kind: 'terminal', x: 3410, y: 570, label: 'RED SOCIAL' },
  ],
  exit: {
    x: 3420,
    y: 520,
    nextLevelId: LEVEL_2_ID,
    completionTitle: '¡¡MATCH ENCONTRADO!!',
    dialogue: [
      'Buscando nuevas conexiones a ver qué aparece por acá...',
      'Analizando perfiles...',
      'Buscando intereses en común...',
      '¡CONEXIÓN ENCONTRADA!',
      'Vicky: ¿Opa... quién es este galán?',
      'Vicky: A ver... estudiante de Ingeniería en Informática...',
      'Vicky: Mmm... parece interesante.',
      'Renzo: Holis...',
      'Vicky: ¿Holis? JAJA.',
      'Renzo: Bueno... había que empezar por algún lado.',
      'Vicky: Tenés razón. Hola, Renzo.',
      '❤️ MATCH',
      'Vicky: Bueno... veremos qué sale de esto.',
      'Renzo: Yo digo que puede salir algo bueno.',
      'Y sin saberlo...',
      '...ese pequeño mensaje estaba a punto de convertirse en algo mucho más grande.',
      'Porque algunos matches duran un rato...',
      '...y otros terminan durando 7 años. ❤️',
    ],
  },
};
